config/routes.rb
Rails.application.routes.draw do
  resources :hints

end

app/models/hint.rb
class Hint < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  before_action :set_hint, only: [:show, :edit, :update, :destroy]

  # GET /hints
  # GET /hints.json
  def index
    @hints = Hint.all
  end

  # GET /hints/1
  # GET /hints/1.json
  def show
  end

  # GET /hints/new
  def new
    @hint = Hint.new
  end

  # GET /hints/1/edit
  def edit
  end

  # POST /hints
  # POST /hints.json
  def create
    @hint = Hint.new(hint_params)

    respond_to do |format|
      if @hint.save
        format.html { redirect_to @hint, notice: 'Hint was successfully created.' }
        format.json { render :show, status: :created, location: @hint }
      else
        format.html { render :new }
        format.json { render json: @hint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hints/1
  # PATCH/PUT /hints/1.json
  def update
    respond_to do |format|
      if @hint.update(hint_params)
        format.html { redirect_to @hint, notice: 'Hint was successfully updated.' }
        format.json { render :show, status: :ok, location: @hint }
      else
        format.html { render :edit }
        format.json { render json: @hint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hints/1
  # DELETE /hints/1.json
  def destroy
    @hint.destroy
    respond_to do |format|
      format.html { redirect_to hints_url, notice: 'Hint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hint
      @hint = Hint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hint_params
      params.require(:hint).permit(:riddle, :found, :lat, :lon, :found_by, :next_hint)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/views/hints/_form.html.erb
<%= form_for(@hint) do |f| %>
  <% if @hint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hint.errors.count, "error") %> prohibited this hint from being saved:</h2>

      <ul>
      <% @hint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :riddle %><br>
    <%= f.text_area :riddle %>
  </div>
  <div class="field">
    <%= f.label :found %><br>
    <%= f.check_box :found %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :found_by %><br>
    <%= f.number_field :found_by %>
  </div>
  <div class="field">
    <%= f.label :next_hint %><br>
    <%= f.text_field :next_hint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hints/edit.html.erb
<h1>Editing Hint</h1>

<%= render 'form' %>

<%= link_to 'Show', @hint %> |
<%= link_to 'Back', hints_path %>

app/views/hints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hints</h1>

<table>
  <thead>
    <tr>
      <th>Riddle</th>
      <th>Found</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Found by</th>
      <th>Next hint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hints.each do |hint| %>
      <tr>
        <td><%= hint.riddle %></td>
        <td><%= hint.found %></td>
        <td><%= hint.lat %></td>
        <td><%= hint.lon %></td>
        <td><%= hint.found_by %></td>
        <td><%= hint.next_hint %></td>
        <td><%= link_to 'Show', hint %></td>
        <td><%= link_to 'Edit', edit_hint_path(hint) %></td>
        <td><%= link_to 'Destroy', hint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hint', new_hint_path %>

app/views/hints/new.html.erb
<h1>New Hint</h1>

<%= render 'form' %>

<%= link_to 'Back', hints_path %>

app/views/hints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Riddle:</strong>
  <%= @hint.riddle %>
</p>

<p>
  <strong>Found:</strong>
  <%= @hint.found %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @hint.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @hint.lon %>
</p>

<p>
  <strong>Found by:</strong>
  <%= @hint.found_by %>
</p>

<p>
  <strong>Next hint:</strong>
  <%= @hint.next_hint %>
</p>

<%= link_to 'Edit', edit_hint_path(@hint) %> |
<%= link_to 'Back', hints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScavengerHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>